10 new product page design
mrdigre/SSR-ReactDemo pull request #18
Opened 2023-08-29 18:35 UTC by mrdigre

@MiltonTulli check new product page styling

2023-08-29 19:14 UTC, MiltonTulli requested changes
Please include a proper description of your work. Don't tag me on the description but do request review through github. Since this pr is mainly ui would be nice to see some screenshots at the description. 
Also link properly the issue you pretend to close. 


Regarding your changes: 
- Page still doesn't look as expected. See issue description and code template included there. 
- "Add to cart" button looks bad (maybe you re behind main branch)
- Quantity selector is broken. 
- Page doesnt look good on mobile. 
![Screenshot 2023-08-29 at 16 08 34](https://github.com/mrdigre/SSR-ReactDemo/assets/25844967/be425773-8ed8-4629-8f43-922a44725deb)
![Screenshot 2023-08-29 at 16 08 23](https://github.com/mrdigre/SSR-ReactDemo/assets/25844967/26ebe700-c881-4093-a025-9fb5397b9532)
![Screenshot 2023-08-29 at 16 08 19](https://github.com/mrdigre/SSR-ReactDemo/assets/25844967/a714a5c9-457c-4312-99d0-81bff78c59e6)

2023-09-01 23:14 UTC, MiltonTulli requested changes

2023-09-01 23:14 UTC, MiltonTulli commented on src/app/components/CartButton.tsx
> +    window.alert("Product added successfully");
This notification should be inside addToCart function

2023-09-01 23:14 UTC, MiltonTulli commented on src/app/products/[id]/page.tsx
> +                    </div> */}
Remove commented code

2023-09-07 15:09 UTC, mrdigre commented
- Product page styling modified considering the provided template:
![image](https://github.com/mrdigre/SSR-ReactDemo/assets/99774063/c024d8f9-2494-44ef-90cf-1345735db478)
- Add to Cart button was behind main branch.
![image](https://github.com/mrdigre/SSR-ReactDemo/assets/99774063/f18b956e-007e-4c71-928d-045ff32b440e)- 
- Quantity selector functionality fixed
- Mobile styling fixed.

Additionally worked on Cart styling on this branch.

2023-09-13 02:04 UTC, MiltonTulli approved these changes
Looks good to me

2023-09-13 02:04 UTC, MiltonTulli commented on src/app/components/Cart.tsx
> +
Remove this comments

2023-09-13 02:25 UTC, merged