Cart context and components
mrdigre/SSR-ReactDemo pull request #9
Opened 2023-08-08 23:11 UTC by mrdigre

2023-08-08 23:14 UTC, MiltonTulli requested changes

2023-08-08 23:14 UTC, MiltonTulli commented on src/app/cart/page.tsx
> +   <div>hi</div>
WTF is this? Please remove if is unnecesary

2023-08-12 19:17 UTC, mrdigre commented
@MiltonTulli you broke the code.

2023-08-15 16:22 UTC, MiltonTulli reviewed
Just a few comments. Also run `npm run lint` and fix lint issues

2023-08-15 16:22 UTC, MiltonTulli commented on src/app/components/CartButton.tsx
> +    window.alert("Product added succesfully")
You could implement something like https://www.npmjs.com/package/react-toastify for notifications

2023-08-15 16:22 UTC, MiltonTulli commented on src/app/components/CartButton.tsx
> +    window.alert("Product added succesfully")
Even the `addToCart` function from context could be the one that triggers the notification.

2023-08-15 16:22 UTC, MiltonTulli commented on src/app/components/Cart.tsx
> +                            return aggregatedItems;
This logic is to find duplicated values, right? I think you should handle this when adding product to cart, not when consuming items.

2023-08-15 16:22 UTC, MiltonTulli commented on src/app/contexts/CartContext.tsx
> +  console.log("CartProvider - cartItems:", cartItems);
You can remove log

2023-08-17 14:33 UTC, merged